name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Redwood Build, Lint, Diagnostics, and Tests
        uses: redwoodjs/project-ci-action@v0.1.1
