name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my-portfolio
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Redwood Build, Lint, Diagnostics, and Tests
        uses: redwoodjs/project-ci-action@v0.1.1
